inherit_from: .rubocop_todo.yml

require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  SuggestExtensions: false
  Exclude:
      - vendor/**/*

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Lint/Debugger:
  Exclude:
    - script/console
Lint/EmptyInPattern:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Exclude:
    - lib/jekyll-feed/page-without-a-file.rb

Performance/MapCompact:
  Enabled: true
Performance/RedundantEqualityComparisonBlock:
  Enabled: true
Performance/RedundantSplitRegexpArgument:
  Enabled: true

Style/InPatternThen:
  Enabled: false
Style/MultilineInPatternThen:
  Enabled: false
Style/QuotedSymbols:
  Enabled: true
