language: ruby
os: linux
dist: xenial
cache: bundler
rvm:
- &latest_ruby 2.7
- 2.5
env:
  - JEKYLL_VERSION="~> 3.7.0"
  - JEKYLL_VERSION="~> 3.8.0"
  - JEKYLL_VERSION="~> 4.0"
jobs:
  include:
  # GitHub Pages
  - rvm: 2.5
    env: &githubpages
      - JEKYLL_VERSION="= 3.9.0"
      - GITHUB_PAGES=1
    before_install: &addkramdowngfm
      - gem update --system
      - bundle add kramdown-parser-gfm
  - rvm: *latest_ruby
    env: *githubpages
    before_install: *addkramdowngfm
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/
before_install:
- gem update --system
install:
- travis_retry script/bootstrap
script: script/cibuild
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.org#jekyll
    template:
    - "%{repository}#%{build_number} %{message} %{build_url}"
  email:
    on_success: never
    on_failure: change
deploy:
  provider: rubygems
  api_key:
    secure: O8fGRnM6OJCqC2BlVE1BqYfq5aR19ulpiHhQwRiHbtSCh8H4rYt7FLsuOwSTtRQjhWYRRSpdRt2ilfQ6PY6Jx1UkxZq5zo9QAPQ9tKxiFTm7gBpZAiAgb06eyaMBSzyQ8qe2qccaFI6CiZhsiaGMsdKsWuYpuoPmdLPd7aDyYJs=
  gem: jekyll-sitemap
  on:
    tags: true
    repo: jekyll/jekyll-sitemap
    condition: "$GITHUB_PAGES == 1"
