language: ruby
os: linux
dist: xenial
cache: bundler
rvm:
- &latest_ruby 2.7
- 2.5
env:
  - JEKYLL_VERSION="~> 3.7.0"
  - JEKYLL_VERSION="~> 3.8.0"
  - JEKYLL_VERSION="~> 4.0"
jobs:
  include:
  # GitHub Pages
  - rvm: 2.5
    env:
    - JEKYLL_VERSION="= 3.9.0"
    - GITHUB_PAGES=1
  - rvm: *latest_ruby
    env:
    - JEKYLL_VERSION="= 3.9.0"
    - GITHUB_PAGES=1
before_install:
- gem update --system
install:
- travis_retry script/bootstrap
script: script/cibuild
