language: ruby
rvm:
- 2.1
- 2.0.0
- 1.9.3
before_script: bundle update
script: "script/cibuild"
sudo: false
cache: bundler
env:
  matrix:
    - JEKYLL_VERSION="~> 2.0"
    - JEKYLL_VERSION="3.0.0.pre.beta1"
